#!/usr/bin/env python
# coding: utf-8

# In[1]:


#numpy
import numpy as np
print("1d array")
a = np.array([1,3])
print(a)
print(" ")
d = np.array([1,2])
print(d)
print(" ")
print("2d array")
b = np.array([[1,2],[4,5]])
c = np.array([[2,4],[5,6]])
print(b)
print(" ")
print(c)
print(" ")
print(np.dot(a,d),"\n")#inner products
print(np.dot(a,b),"\n")#matrix and vector product
print(np.dot(b,c),"\n")#matrix and matrix product


# In[2]:


#Scipy 
from scipy.misc import imread,imsave, imresize 
img = imread("https://blog.playo.co/wp-content/uploads/2017/03/table-tennis-shots.jpg")
print(img.dtype, img.shape) 


# In[7]:





# In[ ]:





# In[ ]:




